# document: https://github.com/realm/SwiftLint

# 無効にするルール
disabled_rules:
- multiple_closures_with_trailing_closure # 複数のクロージャーの場合でも、trailing closureを利用したいため
- empty_enum_arguments # enumの引数を省略したいため

# opt-inルールの中で無効にするルール
- conditional_returns_on_newline # ガード文などは簡潔に一行で記述したいため
- discouraged_optional_collection # PHImageManagerの既存仕様のため
- explicit_enum_raw_value # 暗黙的なraw値で問題ないため
- explicit_type_interface # 型推論を利用したいため
- fatal_error_message # メッセージは不要なため
- file_header # ヘッダには特に決まりがないため
- lower_acl_than_parent # 対応不可のため
- no_extension_access_modifier # extension_access_modifierを優先するため
- no_grouping_extension # グルーピングにextensionを利用したいため
- strict_fileprivate # fileprivateを利用したいため
- switch_case_on_newline # caseと同じ行に記述したいため
- trailing_closure # RxSwiftのOnNextでwarningが出るため

# defaultルール以外にopt-inから採用するルール
opt_in_rules:
- sorted_imports
- prohibited_super_call
- overridden_super_call
- operator_usage_whitespace
- force_unwrapping
- first_where
- explicit_init
- empty_count
- closure_spacing

# Lint対象に追加するパス
included:
- Otofuda-iOS
# - Otofuda-iOSTests
# - Otofuda-iOSUITests

# Lint対象から除外するパス
excluded:
- Carthage
- Pods
- MyLibraryDemoTests

# 1行の文字列制限
line_length:
- 200   # warning
- 300   # error

# 型の行数制限
type_body_length:
- 400   # warning
- 600   # error

# 1ファイルの行数制限
file_length:
- 500   # warning
- 1000  # error

# メソッドの行数制限
function_body_length:
- 100   # warning
- 200   # error

type_name:
  min_length: 2 
  max_length: 40

identifier_name:
  min_length: 1 # 変数名が１文字以上なら許可に変更
  excluded: # excluded via string array
    - id
    - URL
    - x
    - y
    - vc
    - on
  reporter: "xcode"
